Repository Loopring/protocols, pull requests merged in 2019-06, with the labels that each got.

#211 [Protocol3] Implemented skipping of expensive token withdrawals while distributing
  packages/loopring_v3/ABI/version30/IExchange.abi
  packages/loopring_v3/contracts/iface/IExchange.sol
  packages/loopring_v3/contracts/impl/Exchange.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeWithdrawals.sol
  packages/loopring_v3/contracts/lib/ERC20SafeTransfer.sol
  packages/loopring_v3/contracts/test/AccountContract.sol
  packages/loopring_v3/contracts/test/tokens/TEST.sol
  packages/loopring_v3/test/testExchangeDepositWithdraw.ts
  packages/loopring_v3/test/testExchangeUtil.ts
  packages/loopring_v3/util/Artifacts.ts
Labels: bug

#218 [Protocol3] Implementation more admin-functions for UserStakingPool
  packages/loopring_v3/contracts/iface/IUserStakingPool.sol
  packages/loopring_v3/contracts/impl/UserStakingPool.sol
  packages/loopring_v3/contracts/impl/libstaking/UserStakingPoolAdmin.sol
  packages/loopring_v3/contracts/impl/libstaking/UserStakingPoolAuction.sol
  packages/loopring_v3/contracts/impl/libstaking/UserStakingPoolBase.sol
Labels: core_feature

#221 [Protocol3] Calldata compression
  packages/loopring_v3/ABI/version30/IBlockVerifier.abi
  packages/loopring_v3/ABI/version30/IDecompressor.abi
  packages/loopring_v3/ABI/version30/IExchange.abi
  packages/loopring_v3/ABI/version30/ILoopringV3.abi
  packages/loopring_v3/contracts/iface/IBlockVerifier.sol
  packages/loopring_v3/contracts/iface/IDecompressor.sol
  packages/loopring_v3/contracts/iface/IExchange.sol
  packages/loopring_v3/contracts/impl/BlockVerifier.sol
  packages/loopring_v3/contracts/impl/Exchange.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeGenesis.sol
  packages/loopring_v3/contracts/lib/BytesUtil.sol
  packages/loopring_v3/contracts/lib/LzDecompressor.sol
  packages/loopring_v3/contracts/test/Operator.sol
  packages/loopring_v3/operator/create_block.py
  packages/loopring_v3/operator/generate_keys.py
  packages/loopring_v3/operator/state.py
  packages/loopring_v3/package.json
  packages/loopring_v3/proto_blocks/deposit.json
  packages/loopring_v3/proto_blocks/trade.json
  packages/loopring_v3/test/bitarray.ts
  packages/loopring_v3/test/bitstream.ts
  packages/loopring_v3/test/compression.ts
  packages/loopring_v3/test/logs.ts
  packages/loopring_v3/test/rings_config.ts
  packages/loopring_v3/test/simulator.ts
  packages/loopring_v3/test/testClaimable.ts
  packages/loopring_v3/test/testCompression.ts
  packages/loopring_v3/test/testExchangeBlocks.ts
  packages/loopring_v3/test/testExchangeCancel.ts
  packages/loopring_v3/test/testExchangeUtil.ts
  packages/loopring_v3/test/testExchangeWithdrawalMode.ts
  packages/loopring_v3/test/testOwnable.ts
  packages/loopring_v3/test/types.ts
  packages/loopring_v3/tsconfig.json
  packages/loopring_v3/util/Artifacts.ts
Labels: core_feature, enhancement

#232 [Protocol3] Add MintableNonTransferableERC20Token and LOOP token
  packages/loopring_v3/contracts/impl/LOOP.sol
  packages/loopring_v3/contracts/lib/MintableERC20.sol
  packages/loopring_v3/contracts/lib/MintableNonTransferableERC20Token.sol
Labels: core_feature, dao

#234 [Protocol3] conditionally emit AccountUpdated event
  packages/loopring_v3/contracts/impl/libexchange/ExchangeAccounts.sol
Labels: enhancement

#233 [Protocol3] Add RoleBasedOperators.sol for DAO management
  packages/loopring_v3/contracts/lib/RoleBasedOperators.sol
Labels: dao

#235 [Loopring3] 20% to DAO and 10% burned
  packages/loopring_v3/contracts/iface/IProtocolFeeManager.sol
Labels: dao
