Repository Loopring/protocols, pull requests merged in 2019-07, with the labels that each got.

#242 [Protocol3] remove our own reputation token
  packages/loopring_v3/contracts/impl/LOOP.sol
  packages/loopring_v3/contracts/lib/MintableERC20.sol
  packages/loopring_v3/contracts/lib/MintableNonTransferableERC20Token.sol
Labels: dao

#241 [Protocol3] Misc small improvements + More tests
  packages/loopring_v3/ABI/version30/AddressUtil.abi
  packages/loopring_v3/ABI/version30/IExchange.abi
  packages/loopring_v3/ABI/version30/ILoopringV3.abi
  packages/loopring_v3/BACKEND.md
  packages/loopring_v3/contracts/iface/IExchange.sol
  packages/loopring_v3/contracts/iface/ILoopringV3.sol
  packages/loopring_v3/contracts/impl/Exchange.sol
  packages/loopring_v3/contracts/impl/LoopringV3.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeAccounts.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeAdmins.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeDeposits.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeGenesis.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeWithdrawals.sol
  packages/loopring_v3/contracts/lib/AddressUtil.sol
  packages/loopring_v3/contracts/lib/ReentrancyGuard.sol
  packages/loopring_v3/contracts/test/AccountContract.sol
  packages/loopring_v3/contracts/test/TransferContract.sol
  packages/loopring_v3/contracts/test/tokens/TEST.sol
  packages/loopring_v3/migrations/4_deploy_protocol.js
  packages/loopring_v3/migrations/5_deploy_test_contracts.js
  packages/loopring_v3/operator/create_block.py
  packages/loopring_v3/operator/state.py
  packages/loopring_v3/test/constants.ts
  packages/loopring_v3/test/float.ts
  packages/loopring_v3/test/logs.ts
  packages/loopring_v3/test/simulator.ts
  packages/loopring_v3/test/testExchangeAdmin.ts
  packages/loopring_v3/test/testExchangeBlockPermutations.ts
  packages/loopring_v3/test/testExchangeBlocks.ts
  packages/loopring_v3/test/testExchangeCancel.ts
  packages/loopring_v3/test/testExchangeDepositWithdraw.ts
  packages/loopring_v3/test/testExchangeNonReentrant.ts
  packages/loopring_v3/test/testExchangeRingSettlement.ts
  packages/loopring_v3/test/testExchangeShutdown.ts
  packages/loopring_v3/test/testExchangeTokens.ts
  packages/loopring_v3/test/testExchangeUtil.ts
  packages/loopring_v3/test/testExchangeWithdrawalMode.ts
  packages/loopring_v3/test/testLoopring.ts
  packages/loopring_v3/test/testOperator.ts
  packages/loopring_v3/test/testTransfers.ts
  packages/loopring_v3/test/types.ts
  packages/loopring_v3/truffle.js
  packages/loopring_v3/util/Artifacts.ts
Labels: enhancement

#290 [Protocol3] allow offchainData even when onchainDataAvailability is on
  packages/loopring_v3/contracts/iface/IExchange.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
Labels: enhancement

#296 [lightcone_v2.js] enable eslint
  packages/lightcone_v2.js/.eslintrc.js
  packages/lightcone_v2.js/README.md
  packages/lightcone_v2.js/package.json
  packages/lightcone_v2.js/src/grpc/grpcClientService.ts
  packages/lightcone_v2.js/src/index.ts
  packages/lightcone_v2.js/src/lib/sign/babyjub.ts
  packages/lightcone_v2.js/src/lib/sign/eddsa.ts
  packages/lightcone_v2.js/src/lib/sign/pedersenHash.ts
  packages/lightcone_v2.js/src/lib/wallet/WalletUtils.ts
  packages/lightcone_v2.js/src/lib/wallet/common/code.ts
  packages/lightcone_v2.js/src/lib/wallet/common/formatter.ts
  packages/lightcone_v2.js/src/lib/wallet/common/index.ts
  packages/lightcone_v2.js/src/lib/wallet/common/request.ts
  packages/lightcone_v2.js/src/lib/wallet/common/response.ts
  packages/lightcone_v2.js/src/lib/wallet/common/schemas.ts
  packages/lightcone_v2.js/src/lib/wallet/common/utils.ts
  packages/lightcone_v2.js/src/lib/wallet/common/validator.ts
  packages/lightcone_v2.js/src/lib/wallet/config/data.ts
  packages/lightcone_v2.js/src/lib/wallet/config/index.ts
  packages/lightcone_v2.js/src/lib/wallet/config/settings.ts
  packages/lightcone_v2.js/src/lib/wallet/config/tokens.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/contracts/AbiFunction.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/contracts/Contract.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/contracts/Contracts.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/contracts/index.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/eth.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/index.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/keystore.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/metaMask.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/mnemonic.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/schemas.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/token.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/transaction.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/utils.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/validator.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/wallet.ts
  packages/lightcone_v2.js/src/lib/wallet/ethereum/walletAccount.ts
  packages/lightcone_v2.js/src/lib/wallet/index.ts
  packages/lightcone_v2.js/src/model/types.ts
  packages/lightcone_v2.js/src/sign/exchange.ts
  packages/lightcone_v2.js/src/wallet/metaMask.ts
  packages/lightcone_v2.js/src/wallet/privateKey.ts
  packages/lightcone_v2.js/tslint.json
Labels: enhancement

#283 [Protocol3] Batched proof verification
  packages/loopring_v3/.soliumignore
  packages/loopring_v3/ABI/version30/IBlockVerifier.abi
  packages/loopring_v3/ABI/version30/IExchange.abi
  packages/loopring_v3/contracts/iface/IBlockVerifier.sol
  packages/loopring_v3/contracts/iface/IExchange.sol
  packages/loopring_v3/contracts/impl/BlockVerifier.sol
  packages/loopring_v3/contracts/impl/Exchange.sol
  packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
  packages/loopring_v3/contracts/test/Operator.sol
  packages/loopring_v3/contracts/thirdparty/BatchVerifier.sol
  packages/loopring_v3/contracts/thirdparty/Verifier.sol
  packages/loopring_v3/test/testBlockVerifier.ts
  packages/loopring_v3/test/testExchangeBlocks.ts
  packages/loopring_v3/test/testExchangeNonReentrant.ts
  packages/loopring_v3/test/testExchangeUtil.ts
  packages/loopring_v3/test/testExchangeWithdrawalMode.ts
  packages/loopring_v3/test/types.ts
Labels: core_feature
